spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_goods?serverTimezone=GMT%2B8
    username: root
    password: 1234
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true